package Processors

import org.apache.spark.sql.functions._
import org.apache.spark.sql.{DataFrame, SparkSession}

object BPeTAProcessor {
  def generateSelectedDF(parsedDF: DataFrame)(implicit spark: SparkSession): DataFrame = {
    import spark.implicits._ // Habilita o uso de $"coluna"
    parsedDF.select(
      $"NSU",
      concat(
        substring($"DHPROC", 7, 4),
        substring($"DHPROC", 4, 2),
        substring($"DHPROC", 1, 2),
        substring($"DHPROC", 12, 2)
      ).as("DHPROC_FORMATADO"),
      $"DHEMI",
      $"IP_TRANSMISSOR",
      $"parsed.BPeTA.infBPe._Id".as("infbpe_id"),
      $"parsed.BPeTA.infBPe._versao".as("infbpe_versao"),
      $"parsed.BPeTA.infBPe.emit.CNPJ".as("emit_cnpj"),
      $"parsed.BPeTA.infBPe.emit.CRT".as("emit_crt"),
      $"parsed.BPeTA.infBPe.emit.IE".as("emit_ie"),
      $"parsed.BPeTA.infBPe.emit.enderEmit.UF".as("enderemit_uf"),
      $"parsed.BPeTA.infBPe.emit.enderEmit.cMun".as("enderemit_cmun"),
      $"parsed.BPeTA.infBPe.emit.enderEmit.nro".as("enderemit_nro"),
      $"parsed.BPeTA.infBPe.emit.enderEmit.xBairro".as("enderemit_xbairro"),
      $"parsed.BPeTA.infBPe.emit.enderEmit.xCpl".as("enderemit_xcpl"),
      $"parsed.BPeTA.infBPe.emit.enderEmit.xLgr".as("enderemit_xlgr"),
      $"parsed.BPeTA.infBPe.emit.enderEmit.xMun".as("enderemit_xmun"),
      $"parsed.BPeTA.infBPe.emit.xFant".as("emit_xfant"),
      $"parsed.BPeTA.infBPe.emit.xNome".as("emit_xnome"),
      $"parsed.BPeTA.infBPe.ide.UFFim".as("ide_uffim"),
      $"parsed.BPeTA.infBPe.ide.UFIni".as("ide_ufini"),
      $"parsed.BPeTA.infBPe.ide.cBP".as("ide_cbp"),
      $"parsed.BPeTA.infBPe.ide.cDV".as("ide_cdv"),
      $"parsed.BPeTA.infBPe.ide.cMunFim".as("ide_cmunfim"),
      $"parsed.BPeTA.infBPe.ide.cMunIni".as("ide_cmunini"),
      $"parsed.BPeTA.infBPe.ide.cUF".as("ide_cuf"),
      $"parsed.BPeTA.infBPe.ide.dhEmi".as("ide_dhemi"),
      $"parsed.BPeTA.infBPe.ide.indPres".as("ide_indpres"),
      $"parsed.BPeTA.infBPe.ide.mod".as("ide_mod"),
      $"parsed.BPeTA.infBPe.ide.modal".as("ide_modal"),
      $"parsed.BPeTA.infBPe.ide.nBP".as("ide_nbp"),
      $"parsed.BPeTA.infBPe.ide.nroBPIATA".as("ide_nrobpiata"),
      $"parsed.BPeTA.infBPe.ide.serie".as("ide_serie"),
      $"parsed.BPeTA.infBPe.ide.tpAmb".as("ide_tpamb"),
      $"parsed.BPeTA.infBPe.ide.tpBPe".as("ide_tpbpe"),
      $"parsed.BPeTA.infBPe.ide.tpCompra".as("ide_tpcompra"),
      $"parsed.BPeTA.infBPe.ide.tpEmis".as("ide_tpemis"),
      $"parsed.BPeTA.infBPe.ide.verProc".as("ide_verproc"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.CST".as("ibscbs_cst"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.cClassTrib".as("ibscbs_cclasstrib"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.gIBSCBS.gCBS.pCBS".as("gcbs_pcbs"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.gIBSCBS.gCBS.vCBS".as("gcbs_vcbs"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.gIBSCBS.gIBSMun.pIBSMun".as("gibsmun_pibsmun"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.gIBSCBS.gIBSMun.vIBSMun".as("gibsmun_vibsmun"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.gIBSCBS.gIBSUF.pIBSUF".as("gibsuf_pibsuf"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.gIBSCBS.gIBSUF.vIBSUF".as("gibsuf_vibsuf"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.gIBSCBS.vBC".as("ibscbs_vbc"),
      $"parsed.BPeTA.infBPe.imp.IBSCBS.gIBSCBS.vIBS".as("ibscbs_vibs"),
      $"parsed.BPeTA.infBPe.imp.vTotDFe".as("imp_vtotdfe"),
      $"parsed.BPeTA.infBPe.infAdic.infCpl".as("infadic_infcpl"),
      $"parsed.BPeTA.infBPe.infPassagem.dhEmb".as("infpassagem_dhemb"),
      $"parsed.BPeTA.infBPe.infPassagem.dhValidade".as("infpassagem_dhvalidade"),
      $"parsed.BPeTA.infBPe.infPassagem.infPassageiro.nDoc".as("infpassageiro_ndoc"),
      $"parsed.BPeTA.infBPe.infPassagem.infPassageiro.tpDoc".as("infpassageiro_tpdoc"),
      $"parsed.BPeTA.infBPe.infPassagem.infPassageiro.xDoc".as("infpassageiro_xdoc"),
      $"parsed.BPeTA.infBPe.infPassagem.infPassageiro.xNome".as("infpassageiro_xnome"),
      $"parsed.BPeTA.infBPe.infRespTec.CNPJ".as("infresptec_cnpj"),
      $"parsed.BPeTA.infBPe.infRespTec.email".as("infresptec_email"),
      $"parsed.BPeTA.infBPe.infRespTec.fone".as("infresptec_fone"),
      $"parsed.BPeTA.infBPe.infRespTec.xContato".as("infresptec_xcontato"),
      $"parsed.BPeTA.infBPe.infValorBPe.Comp".as("infvalorbpe_comp"),
      $"parsed.BPeTA.infBPe.infValorBPe.vBP".as("infvalorbpe_vbp"),
      $"parsed.BPeTA.infBPe.infValorBPe.vDesconto".as("infvalorbpe_vdesconto"),
      $"parsed.BPeTA.infBPe.infValorBPe.vPgto".as("infvalorbpe_vpgto"),
      $"parsed.BPeTA.infBPe.infValorBPe.vTroco".as("infvalorbpe_vtroco"),
      $"parsed.BPeTA.infBPe.infViagem".as("infviagem"),
      $"parsed.BPeTA.infBPe.pag".as("pag"),
      $"parsed.BPeTA.infBPeSupl.qrCodBPe".as("infbpesupl_qrcodbpe"),
      $"parsed._dhConexao".as("dhconexao"),
      $"parsed._ipTransmissor".as("iptransmissor"),
      $"parsed._nPortaCon".as("nportacon"),
      $"parsed._versao".as("versao"),
      $"parsed._xmlns".as("xmlns"),
      $"parsed.protBPe._versao".as("protbpe_versao"),
      $"parsed.protBPe.infProt._Id".as("infprot_id"),
      $"parsed.protBPe.infProt.cStat".as("infprot_cstat"),
      $"parsed.protBPe.infProt.chBPe".as("chave"),
      $"parsed.protBPe.infProt.dhRecbto".as("infprot_dhrecbto"),
      $"parsed.protBPe.infProt.digVal".as("infprot_digval"),
      $"parsed.protBPe.infProt.nProt".as("infprot_nprot"),
      $"parsed.protBPe.infProt.tpAmb".as("infprot_tpamb"),
      $"parsed.protBPe.infProt.verAplic".as("infprot_veraplic"),
      $"parsed.protBPe.infProt.xMotivo".as("infprot_xmotivo")
    )
  }
}