package Processors

import org.apache.spark.sql.{DataFrame, SparkSession}
import org.apache.spark.sql.functions._

object CTeEventoProcessor {
  def generateSelectedDF(parsedDF: DataFrame)(implicit spark: SparkSession): DataFrame = {
    import spark.implicits._

    parsedDF.select(
      // Campos de metadados
      $"NSUSVD",
      concat(
        substring($"DHPROC", 7, 4),
        substring($"DHPROC", 4, 2),
        substring($"DHPROC", 1, 2),
        substring($"DHPROC", 12, 2)
      ).as("DHPROC_FORMATADO"),
      $"DHEVENTO",
      $"IP_TRANSMISSOR",
      $"parsed._dhConexao".as("dhConexao"),
      $"parsed._ipTransmissor".as("ipTransmissor"),
      $"parsed._nPortaCon".as("nPortaCon"),
      $"parsed._versao".as("versao"),
      $"parsed._xmlns".as("xmlns"),
      $"parsed.eventoCTe._xmlns".as("eventoCTe_xmlns"),
      $"parsed.eventoCTe._Id".as("eventoCTe_Id"),
      $"parsed.eventoCTe._versao".as("eventoCTe_versao"),
      $"parsed.eventoCTe.infEvento.CNPJ".as("infEvento_CNPJ"),
      $"parsed.eventoCTe.infEvento.CPF".as("infEvento_CPF"),
      $"parsed.eventoCTe.infEvento._Id".as("infEvento_Id"),
      $"parsed.eventoCTe.infEvento.cOrgao".as("infEvento_cOrgao"),
      $"parsed.eventoCTe.infEvento.chCTe".as("chave"),
      $"parsed.eventoCTe.infEvento.detEvento._versaoEvento".as("detEvento_versaoEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCTe.descEvento".as("evCancCTe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCTe.nProt".as("evCancCTe_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCTe.xJust".as("evCancCTe_xJust"),
      $"parsed.eventoCTe.infEvento.detEvento.evCCeCTe.descEvento".as("evCCeCTe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCCeCTe.infCorrecao".as("evCCeCTe_infCorrecao"), // ARRAY
      $"parsed.eventoCTe.infEvento.detEvento.evCCeCTe.xCondUso".as("evCCeCTe_xCondUso"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.descEvento".as("evCECTe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.dhEntrega".as("evCECTe_dhEntrega"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.dhHashEntrega".as("evCECTe_dhHashEntrega"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.hashEntrega".as("evCECTe_hashEntrega"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.infEntrega".as("evCECTe_infEntrega"), // ARRAY
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.latitude".as("evCECTe_latitude"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.longitude".as("evCECTe_longitude"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.nDoc".as("evCECTe_nDoc"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.nProt".as("evCECTe_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCECTe.xNome".as("evCECTe_xNome"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.MDFe.chMDFe".as("evCTeAutorizadoMDFe_chMDFe"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.MDFe.dhEmi".as("evCTeAutorizadoMDFe_dhEmi"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.MDFe.dhRecbto".as("evCTeAutorizadoMDFe_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.MDFe.modal".as("evCTeAutorizadoMDFe_modal"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.MDFe.nProt".as("evCTeAutorizadoMDFe_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.descEvento".as("evCTeAutorizadoMDFe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.emit.CNPJ".as("evCTeAutorizadoMDFe_emit_CNPJ"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.emit.CPF".as("evCTeAutorizadoMDFe_emit_CPF"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.emit.IE".as("evCTeAutorizadoMDFe_emit_IE"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeAutorizadoMDFe.emit.xNome".as("evCTeAutorizadoMDFe_emit_XNome"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeCanceladoMDFe.MDFe.chMDFe".as("evCTeCanceladoMDFe_chMDFe"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeCanceladoMDFe.MDFe.nProtCanc".as("evCTeCanceladoMDFe_nProtCanc"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeCanceladoMDFe.descEvento".as("evCTeCanceladoMDFe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeComplementar.chCTeCompl".as("evCTeComplementar_chCTeCompl"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeComplementar.descEvento".as("evCTeComplementar_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeComplementar.dhRecbto".as("evCTeComplementar_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeComplementar.nProt".as("evCTeComplementar_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeMultimodal.chCTeVinculado".as("evCTeMultimodal_chCTeVinculado"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeMultimodal.descEvento".as("evCTeMultimodal_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeMultimodal.dhRecbto".as("evCTeMultimodal_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeMultimodal.nProt".as("evCTeMultimodal_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRedespacho.chCTeRedesp".as("evCTeRedespacho_chCTeRedesp"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRedespacho.descEvento".as("evCTeRedespacho_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRedespacho.dhRecbto".as("evCTeRedespacho_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRedespacho.nProt".as("evCTeRedespacho_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRedespachoInter.chCTeRedespInter".as("evCTeRedespachoInter_chCTeRedespInter"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRedespachoInter.descEvento".as("evCTeRedespachoInter_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRedespachoInter.dhRecbto".as("evCTeRedespachoInter_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRedespachoInter.nProt".as("evCTeRedespachoInter_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.CPFFunc".as("evCTeRegPassagem_CPFFunc"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.cUFTransito".as("evCTeRegPassagem_cUFTransito"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.cUnidFiscal".as("evCTeRegPassagem_cUnidFiscal"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.chMDFe".as("evCTeRegPassagem_chMDFe"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.descEvento".as("evCTeRegPassagem_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.dhPass".as("evCTeRegPassagem_dhPass"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.latitude".as("evCTeRegPassagem_latitude"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.longitude".as("evCTeRegPassagem_longitude"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.placa".as("evCTeRegPassagem_placa"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.tpSentido".as("evCTeRegPassagem_tpSentido"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.tpTransm".as("evCTeRegPassagem_tpTransm"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.xFunc".as("evCTeRegPassagem_xFunc"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.xObs".as("evCTeRegPassagem_xObs"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagem.xUnidFiscal".as("evCTeRegPassagem_xUnidFiscal"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.chMDFe".as("evCTeRegPassagemAuto_chMDFe"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.descEvento".as("evCTeRegPassagemAuto_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.NSU".as("evCTeRegPassagemAuto_NSU"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.cIdEquip".as("evCTeRegPassagemAuto_cIdEquip"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.cUFTransito".as("evCTeRegPassagemAuto_cUFTransito"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.dhPass".as("evCTeRegPassagemAuto_dhPass"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.latitude".as("evCTeRegPassagemAuto_latitude"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.longitude".as("evCTeRegPassagemAuto_longitude"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.placa".as("evCTeRegPassagemAuto_placa"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.tpEquip".as("evCTeRegPassagemAuto_tpEquip"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.tpSentido".as("evCTeRegPassagemAuto_tpSentido"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.infPass.xIdEquip".as("evCTeRegPassagemAuto_xIdEquip"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAuto.tpTransm".as("evCTeRegPassagemAuto_tpTransm"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAutoMDFe.chMDFe".as("evCTeRegPassagemAutoMDFe_chMDFe"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeRegPassagemAutoMDFe.descEvento".as("evCTeRegPassagemAutoMDFe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeSubcontratacao.chCTeSubcon".as("evCTeSubcontratacao_chCTeSubcon"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeSubcontratacao.descEvento".as("evCTeSubcontratacao_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeSubcontratacao.dhRecbto".as("evCTeSubcontratacao_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeSubcontratacao.nProt".as("evCTeSubcontratacao_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeSubstituido.chCTeSubstituicao".as("evCTeSubstituido_chCTeSubstituicao"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeSubstituido.descEvento".as("evCTeSubstituido_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeSubstituido.dhRecbto".as("evCTeSubstituido_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evCTeSubstituido.nProt".as("evCTeSubstituido_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCECTe.descEvento".as("evCancCECTe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCECTe.nProt".as("evCancCECTe_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCECTe.nProtCE".as("evCancCECTe_nProtCE"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCTeComplementar.chCTeCompl".as("evCancCTeComplementar_chCTeCompl"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCTeComplementar.descEvento".as("evCancCTeComplementar_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCTeComplementar.dhRecbto".as("evCancCTeComplementar_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancCTeComplementar.nProt".as("evCancCTeComplementar_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancIECTe.descEvento".as("evCancIECTe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancIECTe.nProt".as("evCancIECTe_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancIECTe.nProtIE".as("evCancIECTe_nProtIE"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancPrestDesacordo.descEvento".as("evCancPrestDesacordo_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evCancPrestDesacordo.nProtEvPrestDes".as("evCancPrestDesacordo_nProtEvPrestDes"),
      $"parsed.eventoCTe.infEvento.detEvento.evGTVeAutorizadoCTeOS.chCTeOS".as("evGTVeAutorizadoCTeOS_chCTeOS"),
      $"parsed.eventoCTe.infEvento.detEvento.evGTVeAutorizadoCTeOS.descEvento".as("evGTVeAutorizadoCTeOS_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evGTVeAutorizadoCTeOS.dhRecbto".as("evGTVeAutorizadoCTeOS_dhRecbto"),
      $"parsed.eventoCTe.infEvento.detEvento.evGTVeAutorizadoCTeOS.nProt".as("evGTVeAutorizadoCTeOS_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evIECTe.descEvento".as("evIECTe_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evIECTe.dhHashTentativaEntrega".as("evIECTe_dhHashTentativaEntrega"),
      $"parsed.eventoCTe.infEvento.detEvento.evIECTe.dhTentativaEntrega".as("evIECTe_dhTentativaEntrega"),
      $"parsed.eventoCTe.infEvento.detEvento.evIECTe.hashTentativaEntrega".as("evIECTe_hashTentativaEntrega"),
      $"parsed.eventoCTe.infEvento.detEvento.evIECTe.infEntrega".as("evIECTe_infEntrega"), // ARRAY
      $"parsed.eventoCTe.infEvento.detEvento.evIECTe.nProt".as("evIECTe_nProt"),
      $"parsed.eventoCTe.infEvento.detEvento.evIECTe.tpMotivo".as("evIECTe_tpMotivo"),
      $"parsed.eventoCTe.infEvento.detEvento.evIECTe.xJustMotivo".as("evIECTe_xJustMotivo"),
      $"parsed.eventoCTe.infEvento.detEvento.evPrestDesacordo.descEvento".as("evPrestDesacordo_descEvento"),
      $"parsed.eventoCTe.infEvento.detEvento.evPrestDesacordo.indDesacordoOper".as("evPrestDesacordo_indDesacordoOper"),
      $"parsed.eventoCTe.infEvento.detEvento.evPrestDesacordo.xObs".as("evPrestDesacordo_xObs"),
      $"parsed.eventoCTe.infEvento.dhEvento".as("infEvento_dhEvento"),
      $"parsed.eventoCTe.infEvento.nSeqEvento".as("infEvento_nSeqEvento"),
      $"parsed.eventoCTe.infEvento.tpAmb".as("infEvento_tpAmb"),
      $"parsed.eventoCTe.infEvento.tpEvento".as("infEvento_tpEvento"),
      $"parsed.retEventoCTe._versao".as("retEvento_versao"),
      $"parsed.retEventoCTe.infEvento._Id".as("retInfEvento_Id"),
      $"parsed.retEventoCTe.infEvento.cOrgao".as("retInfEvento_cOrgao"),
      $"parsed.retEventoCTe.infEvento.cStat".as("retInfEvento_cStat"),
      $"parsed.retEventoCTe.infEvento.chCTe".as("retInfEvento_chCTe"),
      $"parsed.retEventoCTe.infEvento.dhRegEvento".as("retInfEvento_dhRegEvento"),
      $"parsed.retEventoCTe.infEvento.nProt".as("retInfEvento_nProt"),
      $"parsed.retEventoCTe.infEvento.nSeqEvento".as("retInfEvento_nSeqEvento"),
      $"parsed.retEventoCTe.infEvento.tpAmb".as("retInfEvento_tpAmb"),
      $"parsed.retEventoCTe.infEvento.tpEvento".as("retInfEvento_tpEvento"),
      $"parsed.retEventoCTe.infEvento.verAplic".as("retInfEvento_verAplic"),
      $"parsed.retEventoCTe.infEvento.xEvento".as("retInfEvento_xEvento"),
      $"parsed.retEventoCTe.infEvento.xMotivo".as("retInfEvento_xMotivo")
    )
  }
}