package Schemas

import org.apache.spark.sql.types._

object CTeEventoSchema {

  def createSchema(): StructType = {
    new StructType()
      .add("_dhConexao", TimestampType, true)
      .add("_ipTransmissor", StringType, true)
      .add("_nPortaCon", LongType, true)
      .add("_versao", DoubleType, true)
      .add("_xmlns", StringType, true)
      .add("eventoCTe", new StructType()
        .add("_xmlns", StringType, true)
        .add("_versao", DoubleType, true)
        .add("infEvento", new StructType()
          .add("CNPJ", LongType, true)
          .add("CPF", LongType, true)
          .add("_Id", StringType, true)
          .add("cOrgao", LongType, true)
          .add("chCTe", DoubleType, true)
          .add("detEvento", new StructType()
            .add("_versaoEvento", DoubleType, true)
            .add("evCCeCTe", new StructType()
              .add("descEvento", StringType, true)
              .add("infCorrecao", ArrayType(
                new StructType()
                  .add("campoAlterado", StringType, true)
                  .add("grupoAlterado", StringType, true)
                  .add("valorAlterado", StringType, true)), true)
              .add("xCondUso", StringType, true), true)
            .add("evCECTe", new StructType()
              .add("descEvento", StringType, true)
              .add("dhEntrega", TimestampType, true)
              .add("dhHashEntrega", TimestampType, true)
              .add("hashEntrega", StringType, true)
              .add("infEntrega", ArrayType(
                new StructType()
                .add("chNFe", DoubleType, true)), true)
              .add("latitude", DoubleType, true)
              .add("longitude", DoubleType, true)
              .add("nDoc", StringType, true)
              .add("nProt", LongType, true)
              .add("xNome", StringType, true), true)
            .add("evCTeAutorizadoMDFe", new StructType()
              .add("MDFe", new StructType()
                .add("chMDFe", DoubleType, true)
                .add("dhEmi", TimestampType, true)
                .add("dhRecbto", TimestampType, true)
                .add("modal", LongType, true)
                .add("nProt", LongType, true), true)
              .add("descEvento", StringType, true)
              .add("emit", new StructType()
                .add("CNPJ", LongType, true)
                .add("CPF", LongType, true)
                .add("IE", LongType, true)
                .add("xNome", StringType, true), true), true)
            .add("evCTeCanceladoMDFe", new StructType()
              .add("MDFe", new StructType()
                .add("chMDFe", DoubleType, true)
                .add("nProtCanc", LongType, true), true)
              .add("descEvento", StringType, true), true)
            .add("evCTeComplementar", new StructType()
              .add("chCTeCompl", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", TimestampType, true)
              .add("nProt", LongType, true), true)
            .add("evCTeMultimodal", new StructType()
              .add("chCTeVinculado", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", TimestampType, true)
              .add("nProt", LongType, true), true)
            .add("evCTeRedespacho", new StructType()
              .add("chCTeRedesp", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", TimestampType, true)
              .add("nProt", LongType, true), true)
            .add("evCTeRedespachoInter", new StructType()
              .add("chCTeRedespInter", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", TimestampType, true)
              .add("nProt", LongType, true), true)
            .add("evCTeRegPassagem", new StructType()
              .add("CPFFunc", LongType, true)
              .add("cUFTransito", LongType, true)
              .add("cUnidFiscal", LongType, true)
              .add("chMDFe", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhPass", TimestampType, true)
              .add("latitude", DoubleType, true)
              .add("longitude", DoubleType, true)
              .add("placa", StringType, true)
              .add("tpSentido", StringType, true)
              .add("tpTransm", StringType, true)
              .add("xFunc", StringType, true)
              .add("xObs", StringType, true)
              .add("xUnidFiscal", StringType, true), true)
            .add("evCTeRegPassagemAuto", new StructType()
              .add("chMDFe", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("infPass", new StructType()
                .add("NSU", LongType, true)
                .add("cIdEquip", LongType, true)
                .add("cUFTransito", LongType, true)
                .add("dhPass", TimestampType, true)
                .add("latitude", DoubleType, true)
                .add("longitude", DoubleType, true)
                .add("placa", StringType, true)
                .add("tpEquip", LongType, true)
                .add("tpSentido", StringType, true)
                .add("xIdEquip", StringType, true), true)
              .add("tpTransm", StringType, true), true)
            .add("evCTeRegPassagemAutoMDFe", new StructType()
              .add("chMDFe", DoubleType, true)
              .add("descEvento", StringType, true), true)
            .add("evCTeSubcontratacao", new StructType()
              .add("chCTeSubcon", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", TimestampType, true)
              .add("nProt", LongType, true), true)
            .add("evCTeSubstituido", new StructType()
              .add("chCTeSubstituicao", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", TimestampType, true)
              .add("nProt", LongType, true), true)
            .add("evCancCECTe", new StructType()
              .add("descEvento", StringType, true)
              .add("nProt", LongType, true)
              .add("nProtCE", LongType, true), true)
            .add("evCancCTeComplementar", new StructType()
              .add("chCTeCompl", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", TimestampType, true)
              .add("nProt", LongType, true), true)
            .add("evCancIECTe", new StructType()
              .add("descEvento", StringType, true)
              .add("nProt", LongType, true)
              .add("nProtIE", LongType, true), true)
            .add("evCancPrestDesacordo", new StructType()
              .add("descEvento", StringType, true)
              .add("nProtEvPrestDes", LongType, true), true)
            .add("evGTVeAutorizadoCTeOS", new StructType()
              .add("chCTeOS", DoubleType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", TimestampType, true)
              .add("nProt", LongType, true), true)
            .add("evIECTe", new StructType()
              .add("descEvento", StringType, true)
              .add("dhHashTentativaEntrega", TimestampType, true)
              .add("dhTentativaEntrega", TimestampType, true)
              .add("hashTentativaEntrega", StringType, true)
              .add("infEntrega", ArrayType(
                new StructType().add("chNFe", DoubleType, true)), true)
              .add("nProt", LongType, true)
              .add("tpMotivo", LongType, true)
              .add("xJustMotivo", StringType, true), true)
            .add("evPrestDesacordo", new StructType()
              .add("descEvento", StringType, true)
              .add("indDesacordoOper", LongType, true)
              .add("xObs", StringType, true), true))
          .add("dhEvento", TimestampType, true)
          .add("nSeqEvento", LongType, true)
          .add("tpAmb", LongType, true)
          .add("tpEvento", LongType, true))
      )
      .add("retEventoCTe", new StructType()
        .add("_versao", DoubleType, true)
        .add("infEvento", new StructType()
          .add("_Id", StringType, true)
          .add("cOrgao", LongType, true)
          .add("cStat", LongType, true)
          .add("chCTe", DoubleType, true)
          .add("dhRegEvento", TimestampType, true)
          .add("nProt", LongType, true)
          .add("nSeqEvento", LongType, true)
          .add("tpAmb", LongType, true)
          .add("tpEvento", LongType, true)
          .add("verAplic", StringType, true)
          .add("xEvento", StringType, true)
          .add("xMotivo", StringType, true)
        )
      )
  }
}
