package Schemas

import org.apache.spark.sql.types._

object CTeEventoSchema {

  def createSchema(): StructType = {
    new StructType()
      .add("_dhConexao", StringType, true)
      .add("_ipTransmissor", StringType, true)
      .add("_nPortaCon", StringType, true)
      .add("_versao", StringType, true)
      .add("_xmlns", StringType, true)
      .add("eventoCTe", new StructType()
        .add("_xmlns", StringType, true)
        .add("_Id", StringType, true)
        .add("_versao", StringType, true)
        .add("infEvento", new StructType()
          .add("CNPJ", StringType, true)
          .add("CPF", StringType, true)
          .add("_Id", StringType, true)
          .add("cOrgao", StringType, true)
          .add("chCTe", StringType, true)
          .add("detEvento", new StructType()
            .add("_versaoEvento", StringType, true)
            .add("evCancCTe", new StructType()
              .add("descEvento", StringType, nullable = true)
              .add("nProt", StringType, nullable = true)
              .add("xJust", StringType, nullable = true))
            .add("evCCeCTe", new StructType()
              .add("descEvento", StringType, true)
              .add("infCorrecao", ArrayType(new StructType()
                  .add("campoAlterado", StringType, true)
                  .add("grupoAlterado", StringType, true)
                  .add("nroItemAlterado", StringType, true)
                  .add("valorAlterado", StringType, true)), true)
              .add("xCondUso", StringType, true), true)
            .add("evCECTe", new StructType()
              .add("descEvento", StringType, true)
              .add("dhEntrega", StringType, true)
              .add("dhHashEntrega", StringType, true)
              .add("hashEntrega", StringType, true)
              .add("infEntrega", ArrayType(new StructType()
                .add("chNFe", StringType, true)), true)
              .add("latitude", StringType, true)
              .add("longitude", StringType, true)
              .add("nDoc", StringType, true)
              .add("nProt", StringType, true)
              .add("xNome", StringType, true), true)
            .add("evCTeAutorizadoMDFe", new StructType()
              .add("MDFe", new StructType()
                .add("chMDFe", StringType, true)
                .add("dhEmi", StringType, true)
                .add("dhRecbto", StringType, true)
                .add("modal", StringType, true)
                .add("nProt", StringType, true), true)
              .add("descEvento", StringType, true)
              .add("emit", new StructType()
                .add("CNPJ", StringType, true)
                .add("CPF", StringType, true)
                .add("IE", StringType, true)
                .add("xNome", StringType, true), true), true)
            .add("evCTeCanceladoMDFe", new StructType()
              .add("MDFe", new StructType()
                .add("chMDFe", StringType, true)
                .add("nProtCanc", StringType, true), true)
              .add("descEvento", StringType, true), true)
            .add("evCTeComplementar", new StructType()
              .add("chCTeCompl", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("nProt", StringType, true), true)
            .add("evCTeMultimodal", new StructType()
              .add("chCTeVinculado", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("nProt", StringType, true), true)
            .add("evCTeRedespacho", new StructType()
              .add("chCTeRedesp", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("nProt", StringType, true), true)
            .add("evCTeRedespachoInter", new StructType()
              .add("chCTeRedespInter", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("nProt", StringType, true), true)
            .add("evCTeRegPassagem", new StructType()
              .add("CPFFunc", StringType, true)
              .add("cUFTransito", StringType, true)
              .add("cUnidFiscal", StringType, true)
              .add("chMDFe", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhPass", StringType, true)
              .add("latitude", StringType, true)
              .add("longitude", StringType, true)
              .add("placa", StringType, true)
              .add("tpSentido", StringType, true)
              .add("tpTransm", StringType, true)
              .add("xFunc", StringType, true)
              .add("xObs", StringType, true)
              .add("xUnidFiscal", StringType, true), true)
            .add("evCTeRegPassagemAuto", new StructType()
              .add("chMDFe", StringType, true)
              .add("descEvento", StringType, true)
              .add("infPass", new StructType()
                .add("NSU", StringType, true)
                .add("cIdEquip", StringType, true)
                .add("cUFTransito", StringType, true)
                .add("dhPass", StringType, true)
                .add("latitude", StringType, true)
                .add("longitude", StringType, true)
                .add("placa", StringType, true)
                .add("tpEquip", StringType, true)
                .add("tpSentido", StringType, true)
                .add("xIdEquip", StringType, true), true)
              .add("tpTransm", StringType, true), true)
            .add("evCTeRegPassagemAutoMDFe", new StructType()
              .add("chMDFe", StringType, true)
              .add("descEvento", StringType, true), true)
            .add("evCTeSubcontratacao", new StructType()
              .add("chCTeSubcon", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("nProt", StringType, true), true)
            .add("evCTeSubstituido", new StructType()
              .add("chCTeSubstituicao", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("nProt", StringType, true), true)
            .add("evCancCECTe", new StructType()
              .add("descEvento", StringType, true)
              .add("nProt", StringType, true)
              .add("nProtCE", StringType, true), true)
            .add("evCancCTeComplementar", new StructType()
              .add("chCTeCompl", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("nProt", StringType, true), true)
            .add("evCancIECTe", new StructType()
              .add("descEvento", StringType, true)
              .add("nProt", StringType, true)
              .add("nProtIE", StringType, true), true)
            .add("evCancPrestDesacordo", new StructType()
              .add("descEvento", StringType, true)
              .add("nProtEvPrestDes", StringType, true), true)
            .add("evGTVeAutorizadoCTeOS", new StructType()
              .add("chCTeOS", StringType, true)
              .add("descEvento", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("nProt", StringType, true), true)
            .add("evIECTe", new StructType()
              .add("descEvento", StringType, true)
              .add("dhHashTentativaEntrega", StringType, true)
              .add("dhTentativaEntrega", StringType, true)
              .add("hashTentativaEntrega", StringType, true)
              .add("infEntrega", ArrayType(new StructType()
                .add("chNFe", StringType, true)), true)
              .add("nProt", StringType, true)
              .add("tpMotivo", StringType, true)
              .add("xJustMotivo", StringType, true), true)
            .add("evPrestDesacordo", new StructType()
              .add("descEvento", StringType, true)
              .add("indDesacordoOper", StringType, true)
              .add("xObs", StringType, true), true))
          .add("dhEvento", StringType, true)
          .add("nSeqEvento", StringType, true)
          .add("tpAmb", StringType, true)
          .add("tpEvento", StringType, true)))
      .add("retEventoCTe", new StructType()
        .add("_versao", StringType, true)
        .add("infEvento", new StructType()
          .add("_Id", StringType, true)
          .add("cOrgao", StringType, true)
          .add("cStat", StringType, true)
          .add("chCTe", StringType, true)
          .add("dhRegEvento", StringType, true)
          .add("nProt", StringType, true)
          .add("nSeqEvento", StringType, true)
          .add("tpAmb", StringType, true)
          .add("tpEvento", StringType, true)
          .add("verAplic", StringType, true)
          .add("xEvento", StringType, true)
          .add("xMotivo", StringType, true)
        )
      )
  }
}
