package Schemas

import org.apache.spark.sql.types._

object NF3eSchema {
  def createSchema(): StructType = {
    new StructType()
      .add("NF3e",
        new StructType()
          .add("_xmlns", StringType, true)
          .add("infNF3e", new StructType()
              .add("NFdet", new StructType()
                  .add("det", ArrayType( new StructType()
                        .add("_nItem", StringType, true)
                        .add("detItem", new StructType()
                            .add("imposto", new StructType()
                                .add("COFINS", new StructType()
                                    .add("CST", StringType, true)
                                    .add("pCOFINS", DoubleType, true)
                                    .add("vBC", DoubleType, true)
                                    .add("vCOFINS", DoubleType, true), true)
                                .add("COFINSEfet", new StructType()
                                    .add("pCOFINSEfet", DoubleType, true)
                                    .add("vBCCOFINSEfet", DoubleType, true)
                                    .add("vCOFINSEfet", DoubleType, true), true)
                                .add("IBSCBS", new StructType()
                                    .add("CST", StringType, true)
                                    .add("cClassTrib", StringType, true)
                                    .add("gIBSCBS", new StructType()
                                        .add("gCBS", new StructType()
                                            .add("gDevTrib", new StructType()
                                                .add("vDevTrib", DoubleType, true), true)
                                            .add("pCBS", DoubleType, true)
                                            .add("vCBS", DoubleType, true), true)
                                        .add("gIBSMun", new StructType()
                                            .add("gDevTrib", new StructType()
                                                .add("vDevTrib", DoubleType, true), true)
                                            .add("pIBSMun", DoubleType, true)
                                            .add("vIBSMun", DoubleType, true), true)
                                        .add("gIBSUF", new StructType()
                                            .add("gDevTrib", new StructType()
                                                .add("vDevTrib", DoubleType, true), true)
                                            .add("pIBSUF", DoubleType, true)
                                            .add("vIBSUF", DoubleType, true), true)
                                        .add("gTribCompraGov", new StructType()
                                            .add("pAliqCBS", StringType, true)
                                            .add("pAliqIBSMun", StringType, true)
                                            .add("pAliqIBSUF", StringType, true)
                                            .add("vTribCBS", DoubleType, true)
                                            .add("vTribIBSMun", DoubleType, true)
                                            .add("vTribIBSUF", DoubleType, true), true)
                                        .add("vBC", DoubleType, true)
                                        .add("vIBS", DoubleType, true), true), true)
                                .add("ICMS00", new StructType()
                                  .add("orig", StringType, true)
                                  .add("CST", StringType, true)
                                  .add("vBC", DoubleType, true)
                                  .add("pICMS", DoubleType, true)
                                  .add("vICMS", DoubleType, true))
                                .add("ICMS40", new StructType()
                                  .add("CST", StringType, true)
                                  .add("cBenef", StringType, true)
                                  .add("vICMSDeson", DoubleType, true))
                                .add("ICMS60", new StructType()
                                  .add("orig", StringType, true)
                                  .add("CST", StringType, true)
                                  .add("vBCSTRet", DoubleType, true)
                                  .add("pST", DoubleType, true)
                                  .add("vICMSSubstituto", DoubleType, true)
                                  .add("vICMSSTRet", DoubleType, true)
                                  .add("vBCFCPSTRet", DoubleType, true)
                                  .add("pFCPSTRet", DoubleType, true)
                                  .add("vFCPSTRet", DoubleType, true)
                                  .add("pRedBCEfet", DoubleType, true)
                                  .add("vBCEfet", DoubleType, true)
                                  .add("pICMSEfet", DoubleType, true)
                                  .add("vICMSEfet", DoubleType, true))
                                .add("ICMS90", new StructType()
                                  .add("orig", StringType, true)
                                  .add("CST", StringType, true)
                                  .add("vBC", DoubleType, true)
                                  .add("pICMS", DoubleType, true)
                                  .add("vICMS", DoubleType, true))
                                .add("PISEfet", new StructType()
                                    .add("pPISEfet", DoubleType, true)
                                    .add("vBCPISEfet", DoubleType, true)
                                    .add("vPISEfet", DoubleType, true), true)
                                .add("indSemCST", StringType, true)
                                .add("retTrib", new StructType()
                                    .add("vBCIRRF", DoubleType, true)
                                    .add("vIRRF", DoubleType, true)
                                    .add("vRetCSLL", DoubleType, true)
                                    .add("vRetCofins", DoubleType, true)
                                    .add("vRetPIS", DoubleType, true), true), true)
                            .add("prod",
                              new StructType()
                                .add("CFOP", StringType, true)
                                .add("cClass", StringType, true)
                                .add("cProd", StringType, true)
                                .add("gMedicao", new StructType()
                                    .add("gMedida", new StructType()
                                        .add("cPosTarif", StringType, true)
                                        .add("pPerdaTran", DoubleType, true)
                                        .add("tpGrMed", StringType, true)
                                        .add("uMed", StringType, true)
                                        .add("vConst", DoubleType, true)
                                        .add("vMed", DoubleType, true)
                                        .add("vMedAnt", DoubleType, true)
                                        .add("vMedAtu", DoubleType, true)
                                        .add("vMedPerdaTran", DoubleType, true), true)
                                    .add("nContrat", StringType, true)
                                    .add("nMed", StringType, true)
                                    .add("tpMotNaoLeitura", StringType, true), true)
                                .add("indOrigemQtd", StringType, true)
                                .add("qFaturada", DoubleType, true)
                                .add("uMed", StringType, true)
                                .add("vItem", DoubleType, true)
                                .add("vProd", DoubleType, true)
                                .add("xProd", StringType, true), true), true), true ), true)
              )
              .add("_Id", StringType, true)
              .add("acessante", new StructType()
                  .add("idAcesso", StringType, true)
                  .add("idCodCliente", StringType, true)
                  .add("latGPS", StringType, true)
                  .add("longGPS", StringType, true)
                  .add("tpAcesso", StringType, true)
                  .add("tpClasse", StringType, true)
                  .add("tpFase", StringType, true)
                  .add("tpGrpTensao", StringType, true)
                  .add("tpModTar", StringType, true)
                  .add("tpSubClasse", StringType, true)
                  .add("xNomeUC", StringType, true), true)
              .add("dest",
                new StructType()
                  .add("CNPJ", StringType, true)
                  .add("CPF", StringType, true)
                  .add("IE", StringType, true)
                  .add("NB", StringType, true)
                  .add("cNIS", StringType, true)
                  .add("idOutros", StringType, true)
                  .add("indIEDest", StringType, true)
                  .add("xNome", StringType, true)
                  .add("enderDest", new StructType()
                      .add("CEP", StringType, true)
                      .add("UF", StringType, true)
                      .add("cMun", StringType, true)
                      .add("nro", StringType, true)
                      .add("xBairro", StringType, true)
                      .add("xCpl", StringType, true)
                      .add("xLgr", StringType, true)
                      .add("xMun", StringType, true), true), true
              )
              .add("emit", new StructType()
                  .add("CNPJ", StringType, true)
                  .add("IE", StringType, true)
                  .add("xFant", StringType, true)
                  .add("xNome", StringType, true)
                  .add("enderEmit",
                    new StructType()
                      .add("CEP", StringType, true)
                      .add("UF", StringType, true)
                      .add("cMun", StringType, true)
                      .add("fone", StringType, true)
                      .add("nro", StringType, true)
                      .add("xBairro", StringType, true)
                      .add("xCpl", StringType, true)
                      .add("xLgr", StringType, true)
                      .add("xMun", StringType, true), true), true)
              .add("gANEEL", new StructType()
                  .add("gHistFat", ArrayType( new StructType()
                        .add("gGrandFat", ArrayType(new StructType()
                              .add("CompetFat", StringType, true)
                              .add("qtdDias", StringType, true)
                              .add("uMed", StringType, true)
                              .add("vFat", DoubleType, true), true), true)
                        .add("xGrandFat", StringType, true), true), true), true)
              .add("gFat", new StructType()
                  .add("CompetFat", StringType, true)
                  .add("codBarras", StringType, true)
                  .add("codDebAuto", StringType, true)
                  .add("dApresFat", StringType, true)
                  .add("dProxLeitura", StringType, true)
                  .add("dVencFat", StringType, true)
                  .add("gPIX", new StructType()
                      .add("urlQRCodePIX", StringType, true), true)
                  .add("nFat", StringType, true), true)
              .add("gGrContrat", ArrayType(new StructType()
                    .add("_nContrat", StringType, true)
                    .add("qUnidContrat", DoubleType, true)
                    .add("tpGrContrat", StringType, true)
                    .add("tpPosTar", StringType, true), true), true)
              .add("gMed", new StructType()
                  .add("_nMed", StringType, true)
                  .add("dMedAnt", StringType, true)
                  .add("dMedAtu", StringType, true)
                  .add("idMedidor", StringType, true), true)
              .add("gRespTec", new StructType()
                  .add("CNPJ", StringType, true)
                  .add("email", StringType, true)
                  .add("fone", StringType, true)
                  .add("xContato", StringType, true), true)
              .add("gSub", new StructType()
                  .add("chNF3e", StringType, true)
                  .add("gNF", new StructType()
                      .add("CNPJ", StringType, true)
                      .add("CompetApur", StringType, true)
                      .add("CompetEmis", StringType, true)
                      .add("hash115", StringType, true)
                      .add("nNF", StringType, true)
                      .add("serie", StringType, true), true)
                  .add("motSub", StringType, true), true)
              .add("ide",
                  new StructType()
                    .add("cDV", StringType, true)
                    .add("cMunFG", StringType, true)
                    .add("cNF", StringType, true)
                    .add("cUF", StringType, true)
                    .add("dhCont", StringType, true)
                    .add("dhEmi", StringType, true)
                    .add("finNF3e", StringType, true)
                    .add("gCompraGov", new StructType()
                        .add("pRedutor", StringType, true)
                        .add("tpEnteGov", StringType, true), true)
                    .add("mod", StringType, true)
                    .add("nNF", StringType, true)
                    .add("nSiteAutoriz", StringType, true)
                    .add("serie", StringType, true)
                    .add("tpAmb", StringType, true)
                    .add("tpEmis", StringType, true)
                    .add("verProc", StringType, true)
                    .add("xJust", StringType, true), true)
              .add("total", new StructType()
                  .add("IBSCBSTot", new StructType()
                      .add("gCBS", new StructType()
                          .add("vCBS", DoubleType, true)
                          .add("vDevTrib", DoubleType, true)
                          .add("vDif", DoubleType, true), true)
                      .add("gIBS", new StructType()
                          .add("gIBSMun", new StructType()
                              .add("vDevTrib", DoubleType, true)
                              .add("vDif", DoubleType, true)
                              .add("vIBSMun", DoubleType, true), true)
                          .add("gIBSUF", new StructType()
                              .add("vDevTrib", DoubleType, true)
                              .add("vDif", DoubleType, true)
                              .add("vIBSUF", DoubleType, true), true)
                          .add("vIBS", DoubleType, true), true)
                      .add("vBCIBSCBS", DoubleType, true), true)
                  .add("ICMSTot", new StructType()
                      .add("vBC", DoubleType, true)
                      .add("vBCST", DoubleType, true)
                      .add("vFCP", DoubleType, true)
                      .add("vFCPST", DoubleType, true)
                      .add("vICMS", DoubleType, true)
                      .add("vICMSDeson", DoubleType, true)
                      .add("vST", DoubleType, true), true)
                  .add("vCOFINS", DoubleType, true)
                  .add("vCOFINSEfet", DoubleType, true)
                  .add("vNF", DoubleType, true)
                  .add("vPIS", DoubleType, true)
                  .add("vPISEfet", DoubleType, true)
                  .add("vProd", DoubleType, true)
                  .add("vRetTribTot",  new StructType()
                      .add("vIRRF", DoubleType, true)
                      .add("vRetCSLL", DoubleType, true)
                      .add("vRetCofins", DoubleType, true)
                      .add("vRetPIS", DoubleType, true), true)
                  .add("vTotDFe", DoubleType, true), true), true
            )
          .add("infNF3eSupl", new StructType() .add("qrCodNF3e", StringType, true), true), true)
      .add("_dhConexao", StringType, true)
      .add("_ipTransmissor", StringType, true)
      .add("_nPortaCon", StringType, true)
      .add("_versao", StringType, true)
      .add("_xmlns", StringType, true)
      .add("protNF3e", new StructType()
          .add("_versao", StringType, true)
          .add("infProt", new StructType()
              .add("_Id", StringType, true)
              .add("cStat", StringType, true)
              .add("chNF3e", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("digVal", StringType, true)
              .add("nProt", StringType, true)
              .add("tpAmb", StringType, true)
              .add("verAplic", StringType, true)
              .add("xMotivo", StringType, true), true), true
      )
  }
}
