package Schemas

import org.apache.spark.sql.types.{ArrayType, StructType, _}

object NFeDetSchema {
  def createSchema(): StructType = {
    new StructType()
      .add("protNFe", new StructType()
        .add("infProt", new StructType()
          .add("chNFe", StringType, nullable = true)
          .add("cStat", StringType, nullable = true)
          .add("dhRecbto", StringType, nullable = true)
        )
      )
      .add("NFe", new StructType()
        .add("infNFe", new StructType()
          .add("ide", new StructType()
            .add("dhEmi", StringType, nullable = true)
            .add("cUF", StringType, nullable = true)
            .add("natOp", StringType, nullable = true)
          )
          .add("emit", new StructType()
            .add("CNPJ", StringType, nullable = true)
            .add("xNome", StringType, nullable = true)
            .add("enderEmit", new StructType()
              .add("xLgr", StringType, nullable = true)
              .add("nro", StringType, nullable = true)
              .add("xBairro", StringType, nullable = true)
              .add("UF", StringType, nullable = true)
            )
          )
          .add("dest", new StructType()
            .add("CNPJ", StringType, nullable = true)
            .add("xNome", StringType, nullable = true)
            .add("enderDest", new StructType()
              .add("xLgr", StringType, nullable = true)
              .add("nro", StringType, nullable = true)
              .add("xBairro", StringType, nullable = true)
              .add("UF", StringType, nullable = true)
            )
          )
          .add("det", ArrayType(new StructType()
            .add("_nItem", StringType, nullable = true)
            .add("prod", new StructType()
              .add("CFOP", StringType, nullable = true)
              .add("CEST", StringType, nullable = true)
              .add("CNPJFab", StringType, nullable = true)
              .add("NCM", StringType, nullable = true)
              .add("EXTIPI", StringType, nullable = true)
              .add("cBarra", StringType, nullable = true)
              .add("cBarraTrib", StringType, nullable = true)
              .add("cBenef", StringType, nullable = true)
              .add("cEAN", StringType, nullable = true)
              .add("cEANTrib", StringType, nullable = true)
              .add("cProd", StringType, nullable = true)
              .add("indEscala", StringType, nullable = true)
              .add("indTot", StringType, nullable = true)
              .add("nFCI", StringType, nullable = true)
              .add("nItemPed", StringType, nullable = true)
              .add("qCom", DoubleType, nullable = true)
              .add("qTrib", DoubleType, nullable = true)
              .add("uCom", StringType, nullable = true)
              .add("uTrib", StringType, nullable = true)
              .add("vDesc", DoubleType, nullable = true)
              .add("vFrete", DoubleType, nullable = true)
              .add("vOutro", DoubleType, nullable = true)
              .add("vProd", DoubleType, nullable = true)
              .add("vSeg", DoubleType, nullable = true)
              .add("vUnCom", DoubleType, nullable = true)
              .add("vUnTrib", DoubleType, nullable = true)
              .add("xPed", StringType, nullable = true)
              .add("xProd", StringType, nullable = true)
              .add("DI", new StructType()
                .add("CNPJ", StringType, nullable = true)
                .add("UFDesemb", StringType, nullable = true)
                .add("UFTerceiro", StringType, nullable = true)
                .add("adi", new StructType()
                  .add("cFabricante", StringType, nullable = true)
                  .add("nAdicao", StringType, nullable = true)
                  .add("nDraw", StringType, nullable = true)
                  .add("nSeqAdic", StringType, nullable = true)
                )
                .add("cExportador", StringType, nullable = true)
                .add("dDI", StringType, nullable = true)
                .add("dDesemb", StringType, nullable = true)
                .add("nDI", StringType, nullable = true)
                .add("tpIntermedio", StringType, nullable = true)
                .add("tpViaTransp", StringType, nullable = true)
                .add("vAFRMM", DoubleType, nullable = true)
                .add("xLocDesemb", StringType, nullable = true)
              )
              .add("gCred", new StructType()
                .add("cCredPresumido", StringType, nullable = true)
                .add("pCredPresumido", DoubleType, nullable = true)
                .add("vCredPresumido", DoubleType, nullable = true)
              )
              .add("infProdNFF", new StructType()
                .add("cOperNFF", StringType, nullable = true)
                .add("cProdFisco", StringType, nullable = true)
              )
              .add("med", new StructType()
                .add("cProdANVISA", StringType, nullable = true)
                .add("vPMC", DoubleType, nullable = true)
                .add("xMotivoIsencao", StringType, nullable = true)
              )
              .add("arma", ArrayType(new StructType()
                .add("descr", StringType, nullable = true)
                .add("nCano", StringType, nullable = true)
                .add("nSerie", StringType, nullable = true)
                .add("tpArma", StringType, nullable = true)
              ))
              .add("veicProd", new StructType()
                .add("CMT", StringType, nullable = true)
                .add("VIN", StringType, nullable = true)
                .add("anoFab", StringType, nullable = true)
                .add("anoMod", StringType, nullable = true)
                .add("cCor", StringType, nullable = true)
                .add("cCorDENATRAN", StringType, nullable = true)
                .add("cMod", StringType, nullable = true)
                .add("chassi", StringType, nullable = true)
                .add("cilin", StringType, nullable = true)
                .add("condVeic", StringType, nullable = true)
                .add("dist", StringType, nullable = true)
                .add("espVeic", StringType, nullable = true)
                .add("lota", StringType, nullable = true)
                .add("nMotor", StringType, nullable = true)
                .add("nSerie", StringType, nullable = true)
                .add("pesoB", StringType, nullable = true)
                .add("pesoL", StringType, nullable = true)
                .add("pot", StringType, nullable = true)
                .add("tpComb", StringType, nullable = true)
                .add("tpOp", StringType, nullable = true)
                .add("tpPint", StringType, nullable = true)
                .add("tpRest", StringType, nullable = true)
                .add("tpVeic", StringType, nullable = true)
                .add("xCor", StringType, nullable = true)
              )
              .add("NVE", ArrayType(StringType))
              .add("detExport", ArrayType(new StructType()
                .add("exportInd", new StructType()
                  .add("chNFe", DoubleType, nullable = true)
                  .add("nRE", StringType, nullable = true)
                  .add("qExport", DoubleType, nullable = true)
                )
                .add("nDraw", StringType, nullable = true)
              ))
              .add("comb", new StructType()
                .add("CIDE", new StructType()
                  .add("qBCProd", DoubleType, nullable = true)
                  .add("vAliqProd", DoubleType, nullable = true)
                  .add("vCIDE", DoubleType, nullable = true)
                )
                .add("CODIF", StringType, nullable = true)
                .add("UFCons", StringType, nullable = true)
                .add("cProdANP", StringType, nullable = true)
                .add("descANP", StringType, nullable = true)
                .add("encerrante", new StructType()
                  .add("nBico", StringType, nullable = true)
                  .add("nBomba", StringType, nullable = true)
                  .add("nTanque", StringType, nullable = true)
                  .add("vEncFin", DoubleType, nullable = true)
                  .add("vEncIni", DoubleType, nullable = true)
                )
                .add("origComb", ArrayType(new StructType()
                  .add("cUFOrig", StringType, nullable = true)
                  .add("indImport", StringType, nullable = true)
                  .add("pOrig", DoubleType, nullable = true)
                ))
                .add("pBio", DoubleType, nullable = true)
                .add("pGLP", DoubleType, nullable = true)
                .add("pGNi", DoubleType, nullable = true)
                .add("pGNn", DoubleType, nullable = true)
                .add("qTemp", DoubleType, nullable = true)
                .add("vPart", DoubleType, nullable = true)
              )
              .add("rastro", ArrayType(new StructType()
                .add("cAgreg", StringType, nullable = true)
                .add("dFab", StringType, nullable = true)
                .add("dVal", StringType, nullable = true)
                .add("nLote", StringType, nullable = true)
                .add("qLote", DoubleType, nullable = true)
              ))
            )
            .add("imposto", new StructType()
              .add("ICMS", new StructType()
                .add("ICMS00", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("modBC", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCP", DoubleType, nullable = true)
                  .add("pICMS", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vFCP", DoubleType, nullable = true)
                  .add("vICMS", DoubleType, nullable = true)
                )
                .add("ICMS02", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("adRemICMS", DoubleType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("qBCMono", DoubleType, nullable = true)
                  .add("vICMSMono", DoubleType, nullable = true)
                )
                .add("ICMS10", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("modBC", StringType, nullable = true)
                  .add("modBCST", StringType, nullable = true)
                  .add("motDesICMSST", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCP", DoubleType, nullable = true)
                  .add("pFCPST", DoubleType, nullable = true)
                  .add("pICMS", DoubleType, nullable = true)
                  .add("pICMSST", DoubleType, nullable = true)
                  .add("pMVAST", DoubleType, nullable = true)
                  .add("pRedBCST", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vBCFCP", DoubleType, nullable = true)
                  .add("vBCFCPST", DoubleType, nullable = true)
                  .add("vBCST", DoubleType, nullable = true)
                  .add("vFCP", DoubleType, nullable = true)
                  .add("vFCPST", DoubleType, nullable = true)
                  .add("vICMS", DoubleType, nullable = true)
                  .add("vICMSST", DoubleType, nullable = true)
                  .add("vICMSSTDeson", DoubleType, nullable = true)
                )
                .add("ICMS15", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("adRemICMS", DoubleType, nullable = true)
                  .add("adRemICMSReten", DoubleType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("qBCMono", DoubleType, nullable = true)
                  .add("qBCMonoReten", DoubleType, nullable = true)
                  .add("vICMSMono", DoubleType, nullable = true)
                  .add("vICMSMonoReten", DoubleType, nullable = true)
                )
                .add("ICMS20", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("indDeduzDeson", StringType, nullable = true)
                  .add("modBC", StringType, nullable = true)
                  .add("motDesICMS", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCP", DoubleType, nullable = true)
                  .add("pICMS", DoubleType, nullable = true)
                  .add("pRedBC", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vBCFCP", DoubleType, nullable = true)
                  .add("vFCP", DoubleType, nullable = true)
                  .add("vICMS", DoubleType, nullable = true)
                  .add("vICMSDeson", DoubleType, nullable = true)
                )
                .add("ICMS30", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("indDeduzDeson", StringType, nullable = true)
                  .add("modBCST", StringType, nullable = true)
                  .add("motDesICMS", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCPST", DoubleType, nullable = true)
                  .add("pICMSST", DoubleType, nullable = true)
                  .add("pMVAST", DoubleType, nullable = true)
                  .add("pRedBCST", DoubleType, nullable = true)
                  .add("vBCFCPST", DoubleType, nullable = true)
                  .add("vBCST", DoubleType, nullable = true)
                  .add("vFCPST", DoubleType, nullable = true)
                  .add("vICMSDeson", DoubleType, nullable = true)
                  .add("vICMSST", DoubleType, nullable = true)
                )
                .add("ICMS40", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("indDeduzDeson", StringType, nullable = true)
                  .add("motDesICMS", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("vICMSDeson", DoubleType, nullable = true)
                )
                .add("ICMS51", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("modBC", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pDif", DoubleType, nullable = true)
                  .add("pICMS", DoubleType, nullable = true)
                  .add("pRedBC", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vICMS", DoubleType, nullable = true)
                  .add("vICMSDif", DoubleType, nullable = true)
                  .add("vICMSOp", DoubleType, nullable = true)
                )
                .add("ICMS53", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("adRemICMS", DoubleType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pDif", DoubleType, nullable = true)
                  .add("qBCMono", DoubleType, nullable = true)
                  .add("vICMSMono", DoubleType, nullable = true)
                  .add("vICMSMonoDif", DoubleType, nullable = true)
                  .add("vICMSMonoOp", DoubleType, nullable = true)
                )
                .add("ICMS60", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCPSTRet", DoubleType, nullable = true)
                  .add("pICMSEfet", DoubleType, nullable = true)
                  .add("pRedBCEfet", DoubleType, nullable = true)
                  .add("pST", DoubleType, nullable = true)
                  .add("vBCEfet", DoubleType, nullable = true)
                  .add("vBCFCPSTRet", DoubleType, nullable = true)
                  .add("vBCSTRet", DoubleType, nullable = true)
                  .add("vFCPSTRet", DoubleType, nullable = true)
                  .add("vICMSEfet", DoubleType, nullable = true)
                  .add("vICMSSTRet", DoubleType, nullable = true)
                  .add("vICMSSubstituto", DoubleType, nullable = true)
                )
                .add("ICMS61", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("adRemICMSRet", DoubleType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("qBCMonoRet", DoubleType, nullable = true)
                  .add("vICMSMonoRet", DoubleType, nullable = true)
                )
                .add("ICMS70", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("indDeduzDeson", StringType, nullable = true)
                  .add("modBC", StringType, nullable = true)
                  .add("modBCST", StringType, nullable = true)
                  .add("motDesICMS", StringType, nullable = true)
                  .add("motDesICMSST", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pICMS", DoubleType, nullable = true)
                  .add("pICMSST", DoubleType, nullable = true)
                  .add("pMVAST", DoubleType, nullable = true)
                  .add("pRedBC", DoubleType, nullable = true)
                  .add("pRedBCST", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vBCST", DoubleType, nullable = true)
                  .add("vICMS", DoubleType, nullable = true)
                  .add("vICMSDeson", DoubleType, nullable = true)
                  .add("vICMSST", DoubleType, nullable = true)
                  .add("vICMSSTDeson", DoubleType, nullable = true)
                )
                .add("ICMS90", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("indDeduzDeson", StringType, nullable = true)
                  .add("modBC", StringType, nullable = true)
                  .add("modBCST", StringType, nullable = true)
                  .add("motDesICMS", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCP", DoubleType, nullable = true)
                  .add("pICMS", DoubleType, nullable = true)
                  .add("pICMSST", DoubleType, nullable = true)
                  .add("pMVAST", DoubleType, nullable = true)
                  .add("pRedBC", DoubleType, nullable = true)
                  .add("pRedBCST", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vBCFCP", DoubleType, nullable = true)
                  .add("vBCST", DoubleType, nullable = true)
                  .add("vFCP", DoubleType, nullable = true)
                  .add("vICMS", DoubleType, nullable = true)
                  .add("vICMSDeson", DoubleType, nullable = true)
                  .add("vICMSST", DoubleType, nullable = true)
                )
                .add("ICMSPart", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("UFST", StringType, nullable = true)
                  .add("modBC", StringType, nullable = true)
                  .add("modBCST", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pBCOp", DoubleType, nullable = true)
                  .add("pFCPST", DoubleType, nullable = true)
                  .add("pICMS", DoubleType, nullable = true)
                  .add("pICMSST", DoubleType, nullable = true)
                  .add("pRedBC", DoubleType, nullable = true)
                  .add("pRedBCST", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vBCFCPST", DoubleType, nullable = true)
                  .add("vBCST", DoubleType, nullable = true)
                  .add("vFCPST", DoubleType, nullable = true)
                  .add("vICMS", DoubleType, nullable = true)
                  .add("vICMSST", DoubleType, nullable = true)
                )
                .add("ICMSSN101", new StructType()
                  .add("CSOSN", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pCredSN", DoubleType, nullable = true)
                  .add("vCredICMSSN", DoubleType, nullable = true)
                )
                .add("ICMSSN102", new StructType()
                  .add("CSOSN", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                )
                .add("ICMSSN201", new StructType()
                  .add("CSOSN", StringType, nullable = true)
                  .add("modBCST", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pCredSN", DoubleType, nullable = true)
                  .add("pFCPST", DoubleType, nullable = true)
                  .add("pICMSST", DoubleType, nullable = true)
                  .add("pMVAST", DoubleType, nullable = true)
                  .add("pRedBCST", DoubleType, nullable = true)
                  .add("vBCFCPST", DoubleType, nullable = true)
                  .add("vBCST", DoubleType, nullable = true)
                  .add("vCredICMSSN", DoubleType, nullable = true)
                  .add("vFCPST", DoubleType, nullable = true)
                  .add("vICMSST", DoubleType, nullable = true)
                )
                .add("ICMSSN202", new StructType()
                  .add("CSOSN", StringType, nullable = true)
                  .add("modBCST", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCPST", DoubleType, nullable = true)
                  .add("pICMSST", DoubleType, nullable = true)
                  .add("pMVAST", DoubleType, nullable = true)
                  .add("pRedBCST", DoubleType, nullable = true)
                  .add("vBCFCPST", DoubleType, nullable = true)
                  .add("vBCST", DoubleType, nullable = true)
                  .add("vFCPST", DoubleType, nullable = true)
                  .add("vICMSST", DoubleType, nullable = true)
                )
                .add("ICMSSN500", new StructType()
                  .add("CSOSN", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCPSTRet", DoubleType, nullable = true)
                  .add("pICMSEfet", DoubleType, nullable = true)
                  .add("pRedBCEfet", DoubleType, nullable = true)
                  .add("pST", DoubleType, nullable = true)
                  .add("vBCEfet", DoubleType, nullable = true)
                  .add("vBCFCPSTRet", DoubleType, nullable = true)
                  .add("vBCSTRet", DoubleType, nullable = true)
                  .add("vFCPSTRet", DoubleType, nullable = true)
                  .add("vICMSEfet", DoubleType, nullable = true)
                  .add("vICMSSTRet", DoubleType, nullable = true)
                  .add("vICMSSubstituto", DoubleType, nullable = true)
                )
                .add("ICMSSN900", new StructType()
                  .add("CSOSN", StringType, nullable = true)
                  .add("modBC", StringType, nullable = true)
                  .add("modBCST", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pCredSN", DoubleType, nullable = true)
                  .add("pICMS", DoubleType, nullable = true)
                  .add("pICMSST", DoubleType, nullable = true)
                  .add("pMVAST", DoubleType, nullable = true)
                  .add("pRedBC", DoubleType, nullable = true)
                  .add("pRedBCST", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vBCST", DoubleType, nullable = true)
                  .add("vCredICMSSN", DoubleType, nullable = true)
                  .add("vICMS", DoubleType, nullable = true)
                  .add("vICMSST", DoubleType, nullable = true)
                )
                .add("ICMSST", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("orig", StringType, nullable = true)
                  .add("pFCPSTRet", DoubleType, nullable = true)
                  .add("pICMSEfet", DoubleType, nullable = true)
                  .add("pRedBCEfet", DoubleType, nullable = true)
                  .add("pST", DoubleType, nullable = true)
                  .add("vBCEfet", DoubleType, nullable = true)
                  .add("vBCFCPSTRet", DoubleType, nullable = true)
                  .add("vBCSTDest", DoubleType, nullable = true)
                  .add("vBCSTRet", DoubleType, nullable = true)
                  .add("vFCPSTRet", DoubleType, nullable = true)
                  .add("vICMSEfet", DoubleType, nullable = true)
                  .add("vICMSSTDest", DoubleType, nullable = true)
                  .add("vICMSSTRet", DoubleType, nullable = true)
                  .add("vICMSSubstituto", DoubleType, nullable = true)
                )
              )
              .add("ICMSUFDest", new StructType()
                .add("pFCPUFDest", DoubleType, nullable = true)
                .add("pICMSInter", DoubleType, nullable = true)
                .add("pICMSInterPart", DoubleType, nullable = true)
                .add("pICMSUFDest", DoubleType, nullable = true)
                .add("vBCFCPUFDest", DoubleType, nullable = true)
                .add("vBCUFDest", DoubleType, nullable = true)
                .add("vFCPUFDest", DoubleType, nullable = true)
                .add("vICMSUFDest", DoubleType, nullable = true)
                .add("vICMSUFRemet", DoubleType, nullable = true)
              )
              .add("II", new StructType()
                .add("vBC", DoubleType, nullable = true)
                .add("vDespAdu", DoubleType, nullable = true)
                .add("vII", DoubleType, nullable = true)
                .add("vIOF", DoubleType, nullable = true)
              )
              .add("IPI", new StructType()
                .add("CNPJProd", StringType, nullable = true)
                .add("IPINT", new StructType()
                  .add("CST", StringType, nullable = true)
                )
                .add("IPITrib", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("pIPI", DoubleType, nullable = true)
                  .add("qUnid", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vIPI", DoubleType, nullable = true)
                  .add("vUnid", DoubleType, nullable = true)
                )
                .add("cEnq", StringType, nullable = true)
                .add("cSelo", StringType, nullable = true)
                .add("qSelo", StringType, nullable = true)
              )
              .add("ISSQN", new StructType()
                .add("cListServ", DoubleType, nullable = true)
                .add("cMun", StringType, nullable = true)
                .add("cMunFG", StringType, nullable = true)
                .add("cPais", StringType, nullable = true)
                .add("cServico", StringType, nullable = true)
                .add("indISS", StringType, nullable = true)
                .add("indIncentivo", StringType, nullable = true)
                .add("vAliq", DoubleType, nullable = true)
                .add("vBC", DoubleType, nullable = true)
                .add("vISSQN", DoubleType, nullable = true)
              )
              .add("PIS", new StructType()
                .add("PISAliq", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("pPIS", DoubleType, nullable = true)
                  .add("vPIS", DoubleType, nullable = true)
                )
                .add("PISNT", new StructType()
                  .add("CST", StringType, nullable = true)
                )
                .add("PISOutr", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("pPIS", DoubleType, nullable = true)
                  .add("qBCProd", DoubleType, nullable = true)
                  .add("vAliqProd", DoubleType, nullable = true)
                  .add("vPIS", DoubleType, nullable = true)
                )
                .add("PISQtde", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("qBCProd", DoubleType, nullable = true)
                  .add("vAliqProd", DoubleType, nullable = true)
                  .add("vPIS", DoubleType, nullable = true)
                )
                .add("PISST", new StructType()
                  .add("indSomaPISST", StringType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("pPIS", DoubleType, nullable = true)
                  .add("qBCProd", DoubleType, nullable = true)
                  .add("vAliqProd", DoubleType, nullable = true)
                  .add("vPIS", DoubleType, nullable = true)
                )
                .add("vTotTrib", DoubleType, nullable = true)
              )
              .add("COFINS", new StructType()
                .add("COFINSAliq", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("pCOFINS", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vCOFINS", DoubleType, nullable = true)
                )
                .add("COFINSNT", new StructType()
                  .add("CST", StringType, nullable = true)
                )
                .add("COFINSOutr", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("pCOFINS", DoubleType, nullable = true)
                  .add("qBCProd", DoubleType, nullable = true)
                  .add("vAliqProd", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vCOFINS", DoubleType, nullable = true)
                )
                .add("COFINSQtde", new StructType()
                  .add("CST", StringType, nullable = true)
                  .add("qBCProd", DoubleType, nullable = true)
                  .add("vAliqProd", DoubleType, nullable = true)
                  .add("vCOFINS", DoubleType, nullable = true)
                )
                .add("COFINSST", new StructType()
                  .add("indSomaCOFINSST", StringType, nullable = true)
                  .add("pCOFINS", DoubleType, nullable = true)
                  .add("qBCProd", DoubleType, nullable = true)
                  .add("vAliqProd", DoubleType, nullable = true)
                  .add("vBC", DoubleType, nullable = true)
                  .add("vCOFINS", DoubleType, nullable = true)
                )
              )
            )
            .add("impostoDevol", new StructType() // Nova estrutura
              .add("IPI", new StructType()
                .add("vIPIDevol", DoubleType, nullable = true)
              )
              .add("pDevol", DoubleType, nullable = true)
            )
            .add("infAdProd", StringType, nullable = true)
            .add("obsItem", new StructType()
              .add("obsCont", new StructType()
                .add("_xCampo", StringType, nullable = true)
                .add("xTexto", StringType, nullable = true)
              )
              .add("obsFisco", new StructType()
                .add("_xCampo", StringType, nullable = true)
                .add("xTexto", StringType, nullable = true)
              )
            )
          ))
        )
      )
  }
}