package Schemas

import org.apache.spark.sql.types._

object NFeEventoSchema {

  def createSchema(): StructType = {

    new StructType()
      .add("_versao", StringType, true)
      .add("_xmlns", StringType, true)
      .add("evento", new StructType()
        .add("_versao", StringType, true)
        .add("infEvento", new StructType()
          .add("CNPJ", StringType, true)
          .add("CPF", StringType, true)
          .add("_Id", StringType, true)
          .add("cOrgao", StringType, true)
          .add("chNFe", StringType, true)
          .add("detEvento", new StructType()
            .add("CPFOper", StringType, true)
            .add("nProt", StringType, nullable = true)
            .add("CTe", new StructType()
              .add("chCTe", StringType, true)
              .add("dhEmi", StringType, true)
              .add("dhEntrega", StringType, true)
              .add("dhHashEntregaCTe", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("hashEntregaCTe", StringType, true)
              .add("latGPS", StringType, true)
              .add("longGPS", StringType, true)
              .add("modal", StringType, true)
              .add("nDoc", StringType, true)
              .add("nProt", StringType, true)
              .add("nProtCTe", StringType, true)
              .add("nProtCanc", StringType, true)
              .add("xNome", StringType, true), true)
            .add("IE", StringType, true)
            .add("MDFe", new StructType()
              .add("chCTe", StringType, true)
              .add("chMDFe", StringType, true)
              .add("dhEmi", StringType, true)
              .add("dhRecbto", StringType, true)
              .add("modal", StringType, true)
              .add("nProt", StringType, true)
              .add("nProtCanc", StringType, true), true)
            .add("PINe", StringType, true)
            .add("UFDest", StringType, true)
            .add("_versao", StringType, true)
            .add("cOrgaoAutor", StringType, true)
            .add("cPostoUF", StringType, true)
            .add("chCTe", StringType, true)
            .add("chMDFe", StringType, true)
            .add("chNFeRefte", StringType, true)
            .add("ctg", new StructType()
              .add("CNPJDest", StringType, true)
              .add("UFDest", StringType, true)
              .add("diaEmi", StringType, true)
              .add("indICMS", StringType, true)
              .add("indICMSST", StringType, true)
              .add("tpEmis", StringType, true)
              .add("vTotalNFe", DoubleType, true), true)
            .add("dPrevEntrega", StringType, true)
            .add("dVistoria", StringType, true)
            .add("descEvento", StringType, true)
            .add("dest", new StructType()
              .add("CNPJ", StringType, true)
              .add("CPF", StringType, true)
              .add("IE", StringType, true)
              .add("UF", StringType, true)
              .add("vICMS", DoubleType, true)
              .add("vNF", DoubleType, true)
              .add("vST", DoubleType, true), true)
            .add("detPag", ArrayType(new StructType()
                .add("CNPJIF", StringType, true)
                .add("CNPJPag", StringType, true)
                .add("CNPJReceb", StringType, true)
                .add("UFPag", StringType, true)
                .add("UFReceb", StringType, true)
                .add("cAut", StringType, true)
                .add("dPag", StringType, true)
                .add("indPag", StringType, true)
                .add("tBand", StringType, true)
                .add("tPag", StringType, true)
                .add("vPag", DoubleType, true)
                .add("xPag", StringType, true), true), true)
            .add("dhEmi", StringType, true)
            .add("dhEntrega", StringType, true)
            .add("dhHashComprovante", StringType, true)
            .add("dhHashTentativaEntrega", StringType, true)
            .add("dhPas", StringType, true)
            .add("dhTentativaEntrega", StringType, true)
            .add("emit", new StructType()
              .add("CNPJ", StringType, true)
              .add("CPF", StringType, true)
              .add("IE", StringType, true)
              .add("xNome", StringType, true), true)
            .add("gImobilizacao", ArrayType(
              new StructType()
                .add("_nItem", StringType, true)
                .add("gControleEstoque", new StructType()
                  .add("qImobilizado", DoubleType, true)
                  .add("uImobilizado", StringType, true), true)
                .add("vCBS", DoubleType, true)
                .add("vIBS", DoubleType, true), true), true)
            .add("hashComprovante", StringType, true)
            .add("hashTentativaEntrega", StringType, true)
            .add("indOffline", StringType, true)
            .add("indQuitacao", StringType, true)
            .add("indRet", StringType, true)
            .add("itensAverbados", ArrayType(new StructType()
                .add("dhAverbacao", StringType, true)
                .add("dhEmbarque", StringType, true)
                .add("enquad", new StructType()
                  .add("cEnq", ArrayType(StringType, true), true), true)
                .add("motAlteracao", StringType, true)
                .add("nDue", StringType, true)
                .add("nItem", StringType, true)
                .add("nItemDue", StringType, true)
                .add("qItem", DoubleType, true), true), true)
            .add("latGPS", StringType, true)
            .add("locVistoria", StringType, true)
            .add("longGPS", StringType, true)
            .add("modalOutro", new StructType()
              .add("tpModal", StringType, true), true)
            .add("modalRodov", new StructType()
              .add("UFCarreta", StringType, true)
              .add("UFCarreta2", StringType, true)
              .add("UFVeic", StringType, true)
              .add("placaCarreta", StringType, true)
              .add("placaCarreta2", StringType, true)
              .add("placaVeic", StringType, true), true)
            .add("nDoc", StringType, true)
            .add("nProtCTeCanc", StringType, true)
            .add("nProtEvento", StringType, true)
            .add("nTentativa", StringType, true)
            .add("postoVistoria", StringType, true)
            .add("sentidoVia", StringType, true)
            .add("tpAutor", StringType, true)
            .add("tpEventoAut", StringType, true)
            .add("tpMotivo", StringType, true)
            .add("tpNF", StringType, true)
            .add("verAplic", StringType, true)
            .add("xCondUso", StringType, true)
            .add("xCorrecao", StringType, true)
            .add("xHistorico", StringType, true)
            .add("xJust", StringType, true)
            .add("xJustMotivo", StringType, true)
            .add("xNome", StringType, true)
            .add("xNomeOper", StringType, true)
            .add("xObs", StringType, true)
            .add("xPostoUF", StringType, true), true)
          .add("dhEvento", StringType, true)
          .add("nSeqEvento", StringType, true)
          .add("tpAmb", StringType, true)
          .add("tpEvento", StringType, true)
          .add("verEvento", StringType, true)))
      .add("retEvento", new StructType()
        .add("_versao", StringType, true)
        .add("infEvento", new StructType()
          .add("CNPJDest", StringType, true)
          .add("CPFDest", StringType, true)
          .add("_Id", StringType, true)
          .add("cOrgao", StringType, true)
          .add("cOrgaoAutor", StringType, true)
          .add("cStat", StringType, true)
          .add("chCTe", StringType, true)
          .add("chMDFe", StringType, true)
          .add("chNFe", StringType, true)
          .add("dhRegEvento", StringType, true)
          .add("emailDest", StringType, true)
          .add("nProt", StringType, true)
          .add("nSeqEvento", StringType, true)
          .add("tpAmb", StringType, true)
          .add("tpEvento", StringType, true)
          .add("verAplic", StringType, true)
          .add("xEvento", StringType, true)
          .add("xMotivo", StringType, true), true)
      )
  }
}
